## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - |
      julia -e '
        if VERSION >= v"0.7.0-DEV.3656"
            using Pkg
        end
        if VERSION < v"0.7.0-DEV.5183"
            Pkg.clone(pwd(), "Nullables")
            Pkg.build("Nullables")
            Pkg.test("Nullables", coverage=true)
        else
            Pkg.build()
            Pkg.test(coverage=true)
        end'
after_success:
  # push coverage results to Coveralls
  - julia -e '
    VERSION >= v"0.7.0-DEV.3656" && using Pkg
    VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("Nullables"))
    Pkg.add("Coverage")
    using Coverage
    Coveralls.submit(Coveralls.process_folder())
    Codecov.submit(Codecov.process_folder())'
